trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ENV: 'dev'                                   # dev | prod
  TF_WORKDIR: '$(System.DefaultWorkingDirectory)/terraform'
  TFVARS_PATH: 'terraform/envs/$(ENV).tfvars'

steps:
- checkout: self


- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'


# - task: TerraformTask@5
#   displayName: 'Terraform init'
#   inputs:
#     provider: 'azurerm'
#     command: 'init'
#     workingDirectory: '$(TF_WORKDIR)'

#     # MESMA Service Connection para backend e provider:
#     backendServiceArm: 'subcription laboratorio'
#     environmentServiceNameAzureRM: 'subcription laboratorio'

#     backendAzureRmResourceGroupName: 'laboratorio'
#     backendAzureRmStorageAccountName: 'aulasluis'
#     backendAzureRmContainerName: 'tfstate'
#     backendAzureRmKey: 'envs/dev/terraform.tfstate'
- task: TerraformTask@5
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    backendServiceArm: 'subcription laboratorio'
    backendAzureRmStorageAccountName: 'aulasluis'
    backendAzureRmContainerName: 'dev'
    backendAzureRmKey: 'terraform.tfstate'

# PLAN lendo o tfvars
# - task: TerraformTask@5
#   displayName: 'Terraform plan'
#   inputs:
#     provider: 'azurerm'
#     command: 'plan'
#     workingDirectory: '$(TF_WORKDIR)'
#     environmentServiceNameAzureRM: 'Azure subscription 1(093ea378-3099-4ff4-b2ec-b80dc1c14243)'
#     commandOptions: '-var-file=$(TFVARS_PATH)'
#     publishPlanResults: 'terraformPlan'

# APPLY (opcional)
# - task: TerraformTask@5
#   displayName: 'Terraform apply'
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     workingDirectory: '$(TF_WORKDIR)'
#     environmentServiceNameAzureRM: 'Azure subscription 1(093ea378-3099-4ff4-b2ec-b80dc1c14243)'
#     commandOptions: '-auto-approve'
