trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ENV: 'dev'                                   # dev | prod
  TF_WORKDIR: 'terraform'
  TFVARS_PATH: 'terraform/envs/$(ENV).tfvars'

steps:
- checkout: self


- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'


- task: AzureCLI@2
  displayName: 'Terraform init (AzureCLI + ARM_*)'
  inputs:
    azureSubscription: 'subcription laboratorio'  # sua nova SC (corrija o nome se tiver typo)
    addSpnToEnvironment: true
    scriptType: bash
    workingDirectory: '$(TF_WORKDIR)'
    scriptLocation: inlineScript
    inlineScript: |
      set -e
      # Exporta ARM_* a partir da Service Connection
      export ARM_CLIENT_ID="$servicePrincipalId"
      export ARM_CLIENT_SECRET="$servicePrincipalKey"
      export ARM_TENANT_ID="$tenantId"
      export ARM_SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
      export ARM_SKIP_PROVIDER_REGISTRATION=true

      # Se estiver usando AAD no backend, MANTENHA use_azuread_auth=true.
      terraform init \
        -backend-config="resource_group_name=laboratorio" \
        -backend-config="storage_account_name=aulasluis" \
        -backend-config="container_name=dev" \
        -backend-config="key=aks/terraform.tfstate" \
        -backend-config="use_azuread_auth=true" \
        -upgrade
# PLAN lendo o tfvars
- task: TerraformTask@5
  displayName: 'Terraform plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(TF_WORKDIR)'
    environmentServiceNameAzureRM: 'Azure subscription 1(093ea378-3099-4ff4-b2ec-b80dc1c14243)'
    commandOptions: '-var-file=$(TFVARS_PATH)'
    publishPlanResults: 'terraformPlan'

# APPLY (opcional)
# - task: TerraformTask@5
#   displayName: 'Terraform apply'
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     workingDirectory: '$(TF_WORKDIR)'
#     environmentServiceNameAzureRM: 'Azure subscription 1(093ea378-3099-4ff4-b2ec-b80dc1c14243)'
#     commandOptions: '-auto-approve'
