trigger:
- main

stages:
- stage: deployDev
  displayName: deploy IAC - DEV
  pool:
    vmImage: ubunto-latest
  jobs:
  - job: deploy
    steps:
    - checkout: self
    - template: 'deploy-template-pipeline.yml'
  
    