trigger: none

stages:
  - template: "./deploy-template-pipeline.yml"
    parameters:
      envs:
      - name: dev
        apply: false
      - name: prod
        apply: false
      - name: abobrinha
        apply: false
      - name: feijao
        apply: false

      