trigger: 
  branches:
    include:
        - tests
    paths:
      include:
        - api/**
pr: none
  

stages:
  - template: '../../base-pipelines/deploy.pipeline.yaml'
    parameters:
      image_name: 'luistickts-api'                
      dockerfile: './api/LuisDev.DemoApp/LuisDev.DemoApp/Dockerfile'
      release_name: 'demoapi'
      chart_path: './helm/app'
      values_file: './api/LuisDev.DemoApp/LuisDev.DemoApp/cicd/demoapp.helm.yaml'
      envs:
      - 'dev'
      - 'prod'
