trigger: none 
pr:
  branches:
    include:
      - tests 
  paths:
    include:
      - api/LuisDev.DemoApp/**

variables:
  DOTNET_VERSION:
  SOLUTION:
  TEST_PROJECTS:

pool:
  vmImage: "ubuntu-latest"

steps:
- template: '../../base-pipelines/pr.pipeline.yaml'
  parameters:
    dotnet_version: dotnet_version
    soluttion_path: soluttion_path
    test_project_path: test_project_path
 