trigger: none # não roda em push
pr:
  branches:
    include:
      - tests 
  paths:
    include:
      - api/LuisDev.DemoApp/**

variables:
  DOTNET_VERSION: "6.0.x"
  BUILD_CONFIG: "Release"
  SOLUTION: "./api/LuisDev.DemoApp/LuisDev.DemoApp.sln"
  TEST_PROJECTS: "./api/LuisDev.DemoApp/LuisDev.DemoApp.Tests/LuisDev.DemoApp.Tests.csproj"
  WARN_AS_ERROR: "true"

pool:
  vmImage: "ubuntu-latest"

steps:
- template: '../../base-pipelines/pr.pipeline.yaml'