trigger: none 
pr:
  branches:
    include:
      - tests 
  paths:
    include:
      - api/LuisDev.DemoApp/**

pool:
  vmImage: "ubuntu-latest"

steps:
- template: '../../base-pipelines/pr.pipeline.yaml'
  parameters:
    dotnet_version:  "6.0.x"
    solution_path:  "./api/LuisDev.DemoApp/LuisDev.DemoApp.sln"
    test_project_path:  "./api/LuisDev.DemoApp/LuisDev.DemoApp.Tests/LuisDev.DemoApp.Tests.csproj"
 